server:
  port: 8082

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:core_db}
    username: ${DB_USER:focusfriends}
    password: ${DB_PASSWORD:focusfriends}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    dev.illiasemenov.focusfriends: DEBUG
